#!/bin/bash
#获取最大分区时间
max_partition(){
    partition="set hive.cli.print.header=flase;
    show partitions $1;"
    max_part=`hive -S -e  "$partition" | grep '^dt' | sort | tail -n 1` #取最新的分区
    echo ${max_part:3:10}
}
date1=`max_partition 'ft_app.ftapp_ybr_a_s_m'`

#获取时间
yesterday=`date +"%Y-%m-%d" -d "-1 days"`
today=`date +"%Y%m%d"`
date_ago=`date -d "$date1 -32 days" +"%Y-%m-%d"`


